#Caleb Iyob,G01257159
#Lab Section 215
#Lab 11

CC=gcc
CFLAGS=-g	-Wall	-std=c89	-pedantic-errors
TARGET=lab11_ciyob_215
LIBS=-lm
$(TARGET):$(TARGET).c
	$(CC)	$(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
clean:
	rm $(TARGET)
